CREATE TABLE IF NOT EXISTS article_clicks (
    click_id SERIAL PRIMARY KEY,
    article_id INTEGER NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    click_time TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);